server:
  address: 127.0.0.1
  port: 9001
spring:
  application:
    name: rionoj-backend-gateway
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: rionoj-backend-user-service
          uri: lb://rionoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: rionoj-backend-question-service
          uri: lb://rionoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: rionoj-backend-judge-service
          uri: lb://rionoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : swagger2
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - rionoj-backend-gateway
